

# Directory for application data
appdir = "/app"

# Directory for log files
logdir = "/var/log"

# Disable logging to files
nologfiles = false

# Enable unsafe RPC commands
unsaferpc = false

# Verbose WebSocket RPC
wrpc-verbose = false

# Logging verbosity level
loglevel = "debug"

# Enable UTXO index
utxoindex = true

# Reset the database before starting the node
reset-db = false

# Target number of outbound peers
outpeers = 8

# Maximum number of inbound peers
maxinpeers = 125

# Maximum number of RPC clients
rpcmaxclients = 100

# Maximum tracked addresses
max-tracked-addresses = 1000

# Enable unsynced mining
enable-unsynced-mining = false

# Enable mainnet mining
enable-mainnet-mining = false

# Use the test network
testnet = false

# Use the development test network
devnet = false

# Use the simulation test network
simnet = false

# Run as an archival node
archival = false

# Enable sanity checks
sanity = false

# Auto-confirm prompts
yes = false

# Enable performance metrics
perf-metrics = false

# Interval for performance metrics in seconds
perf-metrics-interval-sec = 60

# Block template cache lifetime
block-template-cache-lifetime = 60

# Disable UPnP
disable-upnp = false

# Connect only to specified peers at startup
# connect = ["10.0.0.1", "1.2.3.4"]

# Add peers to connect with at startup
# addpeer = ["192.168.1.2:12345"]

# Add an interface and port to listen for connections
listen = "0.0.0.0:16111"

# Disable DNS seed
nodnsseed = false

# Disable gRPC server
nogrpc = false

# External IP address
# externalip = "192.168.1.3"

# Number of asynchronous threads
# async-threads = 4

# RAM scale factor
ram-scale = 1.0

