[package]
name = "api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8.1.0"
actix-rt = "2.5.0"
actix-service = "2.0"
futures-util = "0.3"
reqwest = "0.11"
actix-files = "0.6"
